using Scalesoft.DisplayTool.Renderer.Constants;
using Scalesoft.DisplayTool.Renderer.Utils.Language;

namespace Scalesoft.DisplayTool.Renderer.Widgets.Fhir;

public static class HdrSectionAbbreviationProvider
{
    private static readonly Dictionary<string, LocalizedAbbreviations> m_dictionary =
        new()
        {
            {
                LoincSectionCodes.Allergies,
                SectionTitleAbbreviations.Allergies
            },
            {
                LoincSectionCodes.AdvanceDirectives,
                SectionTitleAbbreviations.AdvanceDirectives
            },
            {
                LoincSectionCodes.Medications,
                SectionTitleAbbreviations.HistoryOfMedicationUse
            },
            {
                LoincSectionCodes.Immunizations,
                SectionTitleAbbreviations.Immunizations
            },
            {
                LoincSectionCodes.PastIllnessHx,
                SectionTitleAbbreviations.HistoryOfPastIllness
            },
            {
                LoincSectionCodes.Problems,
                SectionTitleAbbreviations.ActiveProblems
            },
            {
                LoincSectionCodes.FunctionalStatus,
                SectionTitleAbbreviations.FunctionalStatus
            },
            {
                LoincSectionCodes.Alert,
                SectionTitleAbbreviations.HealthConcerns
            },
            {
                LoincSectionCodes.PlanOfCare,
                SectionTitleAbbreviations.HealthMaintenanceCarePlan
            },
            {
                LoincSectionCodes.PhysicalFindings,
                SectionTitleAbbreviations.PhysicalFindings
            },
            {
                LoincSectionCodes.SignificantResults,
                SectionTitleAbbreviations.RelevantDiagnosticTests
            },
            {
                LoincSectionCodes.HistoryOfMedicalDevices,
                SectionTitleAbbreviations.HistoryOfMedicalDeviceUse
            },
            {
                LoincSectionCodes.SignificantProcedures,
                SectionTitleAbbreviations.HospitalDischargeProcedures
            },
            {
                LoincSectionCodes.CareTeam,
                SectionTitleAbbreviations.PatientCareTeamInformation
            },
            {
                LoincSectionCodes.AdmissionEvaluation,
                SectionTitleAbbreviations.AdmissionEvaluation
            },
            {
                LoincSectionCodes.DischargeDetails,
                SectionTitleAbbreviations.DischargeDetails
            },
            {
                LoincSectionCodes.FamilyHistory,
                SectionTitleAbbreviations.HistoryOfFamilyMember
            },
            {
                LoincSectionCodes.ProceduresHx,
                SectionTitleAbbreviations.HistoryOfProcedures
            },
            {
                LoincSectionCodes.DischargeMedications,
                SectionTitleAbbreviations.DischargeMedication
            },
            {
                LoincSectionCodes.VitalSigns,
                SectionTitleAbbreviations.VitalSigns
            },
            {
                LoincSectionCodes.Synthesis,
                SectionTitleAbbreviations.Synthesis
            },
            {
                LoincSectionCodes.SocialHistory,
                SectionTitleAbbreviations.SocialHistory
            },
            {
                LoincSectionCodes.AdditionalDocuments,
                SectionTitleAbbreviations.AdditionalDocuments
            },
            {
                LoincSectionCodes.PaymentSources,
                SectionTitleAbbreviations.PaymentSources
            },
            {
                LoincSectionCodes.PhysicalExamByBodyAreas,
                SectionTitleAbbreviations.PhysicalExamination
            },
            {
                LoincSectionCodes.HospitalCourse,
                SectionTitleAbbreviations.HospitalCourse
            },
            {
                LoincSectionCodes.HospitalDischargeInstructions,
                SectionTitleAbbreviations.HospitalDischargeInstructions
            },
            {
                LoincSectionCodes.HospitalDischargePhysicalFindings,
                SectionTitleAbbreviations.HospitalDischargePhysicalFindings
            },
            {
                LoincSectionCodes.HistoryOfTravel,
                SectionTitleAbbreviations.HistoryOfTravel
            },
            {
                LoincSectionCodes.HistoryGeneral,
                SectionTitleAbbreviations.GeneralHistory
            },
            {
                LoincSectionCodes.Encounters,
                SectionTitleAbbreviations.Encounters
            },
        };

    public static LocalizedAbbreviations? GetAbbreviation(string sectionCode) =>
        m_dictionary.GetValueOrDefault(sectionCode);
}